/* 规则回归测试：node test.mjs
   直接从 prd-check.html 里抠出规则引擎跑，保证测的就是线上那份。
   合成用例只验「规则还活着」；真实长文档才验「准不准」——见下方说明。 */
import fs from "fs";

const html = fs.readFileSync(new URL("./prd-check.html", import.meta.url), "utf8");
const src = html.split("/*RULES_START*/")[1].split("/*RULES_END*/")[0];
const analyzeDoc = new Function(src + "; return analyzeDoc;")();

const FIXTURE = `# 测试文档
## 第 1 章
| 参数 | 默认值 | 是否需业务确认 |
| --- | --- | --- |
| 相似度阈值 | 0.78 | **是** |
| 需求估算权重 | 25% / 30% / 20% / 25% | 否 |

正文里又说一遍：热度衰减系数 取 0.9。

| 指标 | 符号 | 说明 |
| --- | --- | --- |
| 趋势斜率 | β | 线性回归斜率 |
| LDA 超参 | β | 主题模型超参 |

## 第 3 章
| 参数 | 默认值 |
| --- | --- |
| 相似度阈值 | 0.85 |
| 需求估算权重 | 30% / 40% / 30% |
| 热度衰减系数 | 0.93 |

## 第 4 章 权重
各维度权重：研究 30%、资本 30%、产业 20%、政策 10%

## 第 5 章 数据源
| 数据源 | 可用性 | 角色 |
| --- | --- | --- |
| 专利数据 | 待定 | 辅助信号 |

专利强度按公式计算，权重取 0.35。
专利数量进入图表绘制环节，作为第二坐标轴指标。
专利活跃度参与最终得分归一化。

| 赛道 | 基数 | 缺口 | 测算 |
| --- | --- | --- | --- |
| 具身智能 | 1200 | 数据缺失 | 1200×1.5×1.1 ≈ 1980 |

> 修正说明：原稿将专利库误写为论文库，本版已更正（见附录 B-03）。

建议使用 \`talent-fetch-cli\` 批量拉取。接口地址：https://api.example.cn/v2/search

值得注意的是，系统将自动识别候选人的能力标签（Capability Tagging），模型会实时分析岗位匹配度。
- **第一阶段**：平台自动打标，全面覆盖产业链全链路。
- **第二阶段**：AI 智能分析人才流动趋势，深度挖掘潜在人才。
- **第三阶段**：有效提升匹配效率，实现人岗匹配闭环，持续优化并赋能业务。

综上所述，本方案一方面夯实了数据底座，另一方面助力业务降本增效。

## 第 6 章 产出形态
报告每月生成一次，输出 PDF 与在线页面两种形态。
图表由前端渲染，数据来自中间表。
中间表每日凌晨刷新。
刷新失败时发送告警。
告警接收人见运维表。
历史版本保留 12 个月。
超过保留期的版本自动归档。
归档后仍可按报告编号检索。
检索入口在平台左侧导航。
导出功能支持 CSV 与 XLSX 两种格式。
权限按部门划分，跨部门需申请。
申请流程走内部审批系统。
`;

const EXPECT = [
  "未决伪装", "悬空依赖", "缺失却照算", "补丁痕迹",
  "未验证具体物", "无源数字", "空心自动化", "空心词", "无验收", "口径冲突", "AI 痕迹"
];

const r = analyzeDoc(FIXTURE);
const got = new Set(r.findings.map(f => f.rule));
let bad = 0;

console.log(`阻断 ${r.hi} · 待澄清 ${r.md} · 噪音 ${r.lo} · AI痕迹 ${r.ai}\n`);
for (const rule of EXPECT) {
  const ok = got.has(rule);
  if (!ok) bad++;
  console.log(`${ok ? "✓" : "✗ 没命中"}  ${rule}`);
}

// 口径冲突的四个子项都要在
const kj = r.findings.filter(f => f.rule === "口径冲突").map(f => f.title).join(" | ");
for (const sub of ["同名参数", "符号", "权重加起来"]) {
  const ok = kj.includes(sub);
  if (!ok) bad++;
  console.log(`${ok ? "✓" : "✗ 没命中"}  口径冲突 · ${sub}`);
}

// 每张卡的三段必须齐
for (const f of r.findings) {
  if (!f.impact || !f.who || !f.ask) { console.log(`✗ ${f.rule} 缺 业务影响/找谁/问句`); bad++; }
}

const FIXTURE_EN = `# Talent Insights Platform — Product Requirements Document v2

This document is intended to comprehensively outline the end-to-end architecture across three dimensions.

## 0.1 Global Parameter Registry

| Parameter | Default | Needs sign-off |
| --- | --- | --- |
| Similarity threshold | 0.78 | **Y** |
| Cluster count K | 12 | N |
| Decay coefficient | 0.93 | **Y** |
| Concurrency cap | 4 | N |
| Ranking weight | 0.35 | **Y** |

## 0.2 Data Sources

| Source | Availability | Role |
| --- | --- | --- |
| Resume DB | Ready | Primary |
| Patent data | TBD | Supporting signal |

> Correction note: the previous draft listed the patent DB as a paper DB; corrected in this version (see Appendix B-03).

## 1.3 Scoring Formula

Patent intensity is calculated with a weighted formula; the weight is 0.35.
Patent activity feeds into the final score normalization step.
Patent counts are plotted on the secondary axis of the chart.

## 1.4 Implementation Notes

We recommend the open-source \`talent-fetch-cli\` for bulk pulls, and \`patentview-mcp\` for patent retrieval.
Endpoint: https://api.example-patent.cn/v2/search

It's important to note that the system will automatically identify candidate capability tags, and the model will intelligently analyze role fit in real-time.

- **Phase One**: the platform automatically tags and classifies talent end-to-end.
- **Phase Two**: AI will seamlessly unlock holistic insights across the value chain.
- **Phase Three**: a best-in-class, state-of-the-art engine that will empower stakeholders at scale.

## 2.1 Capability Split

L4 fully automated 12 items (71%), L3 AI-led 5 items (29%), no expert review needed.
Accuracy of semantic classification is 85%+.

Five items: 1.1.1 industry parsing, 1.1.2 course mapping, 1.1.3 goal matching, 1.3.1 standards alignment, 2.1.2 teacher capability, 2.3.2 assessment closure.

## 2.2 Weights

Dimension A 30%, Dimension B 35%, Dimension C 15% weight, Dimension D 25% weight.

## 3. Timeline

This brilliant idea will compress total evaluation time to 20-30 seconds. Rollout completes in 6 months.

Furthermore, this is a revolutionary and game-changing approach.

---
Generated by Claude. Please review before distribution.
`;

const EXPECT_EN = [
  "tableSelfDeclared", "danglingInput", "unverifiedArtifacts", "countMismatch", "weightsOff",
  "unsourcedNumbers", "unsourcedPercent", "pendingScattered", "patchMarks",
  "ungroundedTimeline", "hollowWords", "hypeLeftovers", "aiProse", "aiDisclosed"
];

const re = analyzeDoc(FIXTURE_EN);
const gotEn = new Set(re.findings.map(f => f.k));
console.log(`\n[EN] 阻断 ${re.hi} · 待澄清 ${re.md} · 噪音 ${re.lo} · AI痕迹 ${re.ai}\n`);
for (const k of EXPECT_EN) {
  const ok = gotEn.has(k);
  if (!ok) bad++;
  console.log(`${ok ? "\u2713" : "\u2717 \u6ca1\u547d\u4e2d"}  EN \u00b7 ${k}`);
}
for (const f of re.findings) {
  if (!f.k || !f.p) { console.log(`\u2717 EN ${f.rule} \u7f3a key/\u53c2\u6570`); bad++; }
}

/* ---- 跨文档对照（cross-check.html）---- */
const ccHtml = fs.readFileSync(new URL("./cross-check.html", import.meta.url), "utf8");
const ccSrc = ccHtml.split("/*EXTRACT_START*/")[1].split("/*EXTRACT_END*/")[0];
const cc = new Function(ccSrc + "; return {extractFacts:extractFacts, crossCheck:crossCheck};")();

const CC_ZH_A = `使命型指标体系

维度
含义
指标数
权重
A. 课程与需求适配性
一致性
7项
30%
C. 运行保障支撑度
条件
2项
20%
D. 产出与贡献
结果
3项
20%
合计
17项
100%`;
const CC_ZH_B = `用户端五步路径

• 使命型17项：分A课程与需求适配性（7项，30%）、C运行保障支撑度（2项，15%）、D产出与贡献（3项，25%）`;
const CC_EN_A = `Mission-type indicator system

Dimension
Meaning
Count
Weight
A. Course-demand fit
consistency
7 items
30%
C. Operational support
conditions
2 items
20%
D. Outcomes
results
3 items
20%`;
const CC_EN_B = `Five-step rollout

Mission-type 17 items: A Course-demand fit (7 items, 30%), C Operational support (2 items, 15%), D Outcomes (3 items, 25%)`;

function ccCase(label, a, b, expect) {
  const got = cc.crossCheck([
    { name: "a.txt", lines: a.split("\n") },
    { name: "b.txt", lines: b.split("\n") }
  ]);
  const ok = got.length === expect;
  if (!ok) bad++;
  console.log(`${ok ? "✓" : "✗"}  ${label}：冲突 ${got.length}（期望 ${expect}）${got.length ? " — " + got.map(x => x.label).join("、") : ""}`);
}
console.log("");
ccCase("对照 · 中文", CC_ZH_A, CC_ZH_B, 2);
ccCase("对照 · 英文", CC_EN_A, CC_EN_B, 2);

console.log(bad ? `\n失败 ${bad} 项` : "\n全部通过");
process.exit(bad ? 1 : 0);
